import { chromium } from 'playwright';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const url = process.env.SHIYI_URL || 'http://127.0.0.1:18743';
const screenshotDir = process.env.SHIYI_SCREENSHOT_DIR || path.join(os.tmpdir(), 'shiyi-test-screenshots');
fs.mkdirSync(screenshotDir, { recursive: true });
const browser = await chromium.launch({ headless: true });
const errors = [];

try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  const page = await context.newPage();
  let requestedModel = '';
  await page.route('https://api.deepseek.com/chat/completions', async route => {
    const requestBody = route.request().postDataJSON(); requestedModel = requestBody.model;
    const input = JSON.parse(requestBody.messages.at(-1).content);
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ choices: [{ message: { content: JSON.stringify({ words: input.words.map(item => ({ id: item.id, meaningZh: `${item.term}的测试释义`, example: `他在语境中使用${item.term}。`, distinction: `${item.term}的测试辨析`, collocation: `${item.term}搭配`, memoryCue: `${item.term}记忆线索` })), story: input.words.map(item => item.term).join('，') + '，共同组成一段测试故事。' }) } }], usage: { prompt_tokens: 100, completion_tokens: 200, total_tokens: 300 } }) });
  });
  await page.route('https://api.deepseek.com/user/balance', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ is_available: true, balance_infos: [{ currency: 'CNY', total_balance: '99.00' }] }) }));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: '花生800词', exact: true }).click();
  await page.getByRole('heading', { name: '花生800词', exact: true }).waitFor();
  await page.locator('#peanut-graph canvas').first().waitFor({ state: 'attached' });
  await page.waitForTimeout(1200);
  if (await page.locator('#peanut-graph').getAttribute('data-layout-overlaps') !== '0') throw new Error('Peanut800 overview graph contains overlapping nodes');
  await page.screenshot({ path: path.join(screenshotDir, 'peanut800-desktop.png'), fullPage: true });
  const stats = await page.locator('.peanut-stats').innerText();
  if (!stats.includes('766') || !stats.includes('语义簇')) throw new Error('Peanut800 seed data did not load');
  const graphPixels = await page.locator('#peanut-graph').evaluate(container => [...container.querySelectorAll('canvas')].reduce((total, canvas) => {
    const ctx = canvas.getContext('2d'); if (!ctx) return total;
    const pixels = ctx.getImageData(0, 0, canvas.width, canvas.height).data; let painted = 0;
    for (let i = 3; i < pixels.length; i += Math.max(4, Math.floor(pixels.length / 8000 / 4) * 4)) if (pixels[i] > 0) painted += 1;
    return total + painted;
  }, 0));
  if (graphPixels < 20) throw new Error('Peanut800 graph canvas has no visible drawing');
  const clusterButtons = page.locator('[data-peanut-cluster]');
  if (await clusterButtons.count() < 3) throw new Error('Peanut800 cluster labels were not listed');
  if (await clusterButtons.count() > 21) throw new Error('Peanut800 cluster page exceeds its item limit');
  if (await page.locator('.peanut-word-card').count() !== 12) throw new Error('Peanut800 word page size is incorrect');
  const firstWordPageOne = await page.locator('.peanut-word-card h3').first().innerText();
  await page.locator('[data-peanut-page="word:next"]').click();
  if (await page.locator('.peanut-word-card h3').first().innerText() === firstWordPageOne) throw new Error('Peanut800 word pagination did not advance');
  await page.locator('[data-peanut-page="word:prev"]').click();
  const firstClusterPageOne = await page.locator('[data-peanut-cluster]').nth(1).innerText();
  await page.locator('[data-peanut-page="cluster:next"]').click();
  if (await page.locator('[data-peanut-cluster]').nth(1).innerText() === firstClusterPageOne) throw new Error('Peanut800 cluster pagination did not advance');
  await page.locator('[data-peanut-page="cluster:prev"]').click();
  await clusterButtons.nth(1).click();
  await page.waitForTimeout(800);
  if (await page.locator('[data-peanut-cluster].active').count() !== 1) throw new Error('Peanut800 cluster selection failed');
  if (!await page.locator('.peanut-overview header').innerText().then(text => text.includes('正在查看'))) throw new Error('Peanut800 graph did not focus the selected cluster');
  if (await page.locator('#peanut-graph').getAttribute('data-layout-overlaps') !== '0') throw new Error('Peanut800 focused cluster contains overlapping nodes');
  await page.evaluate(() => new Promise((resolve, reject) => { const request = indexedDB.open('shiyi-ai-settings', 1); request.onupgradeneeded = () => request.result.createObjectStore('settings', { keyPath: 'id' }); request.onerror = () => reject(request.error); request.onsuccess = () => { const db = request.result; const tx = db.transaction('settings', 'readwrite'); tx.objectStore('settings').put({ id: 'deepseek-api-key', value: 'test-deepseek-key', updatedAt: new Date().toISOString() }); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }; }));
  await page.getByRole('button', { name: 'AI 完善本簇', exact: true }).click();
  await page.getByRole('heading', { name: '审核词簇生成结果', exact: true }).waitFor();
  await page.getByRole('button', { name: '审核通过并写入', exact: true }).click();
  if (requestedModel !== 'deepseek-v4-flash') throw new Error('Peanut800 did not share the configured DeepSeek model');
  await page.locator('.peanut-cluster-story').waitFor();
  await page.screenshot({ path: path.join(screenshotDir, 'peanut800-cluster.png'), fullPage: false });
  const recordsBefore = await page.evaluate(() => new Promise((resolve, reject) => {
    const request = indexedDB.open('shiyi-peanut800'); request.onerror = () => reject(request.error); request.onsuccess = () => { const db = request.result; const query = db.transaction('records').objectStore('records').getAll(); query.onerror = () => reject(query.error); query.onsuccess = () => resolve(query.result); };
  }));
  if (recordsBefore.filter(record => record.kind === 'word').length !== 766) throw new Error('Peanut800 IndexedDB word count mismatch');
  if (recordsBefore.filter(record => record.kind === 'cluster_generation').length !== 1) throw new Error('Peanut800 cluster story was not persisted');
  if (!recordsBefore.some(record => record.kind === 'word' && record.meaningZh?.includes('测试释义') && record.examples?.length && record.distinctions?.length && record.collocations?.length && record.memoryCues?.length)) throw new Error('Peanut800 AI cluster fields were not written');
  const usageEntries = await page.evaluate(() => new Promise((resolve, reject) => { const request = indexedDB.open('shiyi-ai-usage'); request.onerror = () => reject(request.error); request.onsuccess = () => { const query = request.result.transaction('requests').objectStore('requests').getAll(); query.onerror = () => reject(query.error); query.onsuccess = () => resolve(query.result); }; }));
  if (!usageEntries.some(entry => entry.model === 'deepseek-v4-flash' && entry.totalTokens === 300)) throw new Error('Peanut800 AI usage was not shared with the AI workspace');
  await page.getByRole('button', { name: '开始回忆', exact: true }).click();
  await page.getByRole('heading', { name: '先回忆，再揭示', exact: true }).waitFor();
  await page.getByRole('button', { name: '揭示答案', exact: true }).click();
  await page.getByRole('button', { name: '记得', exact: true }).click();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  const graph = page.locator('#peanut-graph');
  await page.locator('[data-peanut-open]').first().click();
  await page.locator('.peanut-edit-panel').waitFor();
  const panelBox = await page.locator('.peanut-edit-panel').boundingBox();
  const resizedGraphBox = await graph.boundingBox();
  if (!panelBox || !resizedGraphBox || panelBox.x < resizedGraphBox.x + resizedGraphBox.width - 2) throw new Error('Peanut800 editor did not open to the right of the graph');
  await page.waitForTimeout(500);
  await page.screenshot({ path: path.join(screenshotDir, 'peanut800-editor.png'), fullPage: false });
  await page.locator('#peanut-edit-form textarea[name="example"]').fill('This is a user-authored example.');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const recordsAfter = await page.evaluate(() => new Promise((resolve, reject) => {
    const request = indexedDB.open('shiyi-peanut800'); request.onerror = () => reject(request.error); request.onsuccess = () => { const db = request.result; const query = db.transaction('records').objectStore('records').getAll(); query.onerror = () => reject(query.error); query.onsuccess = () => resolve(query.result); };
  }));
  if (recordsAfter.filter(record => record.kind === 'review_event').length !== 1) throw new Error('Peanut800 review event was not stored');
  if (!recordsAfter.some(record => record.kind === 'word' && record.examples?.includes('This is a user-authored example.'))) throw new Error('Peanut800 edit was not persisted');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: '更多功能', exact: true }).click();
  await page.getByRole('button', { name: '花生800词', exact: true }).click();
  await page.locator('#peanut-graph canvas').first().waitFor({ state: 'attached' });
  await page.waitForTimeout(900);
  await page.screenshot({ path: path.join(screenshotDir, 'peanut800-mobile.png'), fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)) throw new Error('Peanut800 mobile layout overflows horizontally');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: peanut800 import, cluster navigation, graph, active recall, editing, persistence, and mobile layout');
} finally {
  await browser.close();
}
